parser: '@typescript-eslint/parser'
env:
    browser: true
    es6: true
    node: true
    jest: true
    jquery: true
extends:
    - 'eslint:recommended'
    - 'plugin:@typescript-eslint/recommended'
    - 'plugin:@typescript-eslint/recommended-requiring-type-checking'
    - 'plugin:@next/next/recommended'
    - 'prettier'
    - 'next'
    - 'next/core-web-vitals'
plugins:
    - react
    - react-hooks

rules:
    no-duplicate-imports:
        - error
    no-self-compare:
        - error
    no-shadow:
        - off
    '@typescript-eslint/ban-ts-comment':
        - off
    '@typescript-eslint/no-shadow':
        - error
        - {
              builtinGlobals: false,
              hoist: 'never',
              ignoreOnInitialization: true,
              allow: ['InputProps'],
          }
    eqeqeq:
        - error
    no-console:
        - error
        - { allow: ['warn', 'error'] }
    max-params:
        - error
    no-eval:
        - error
    no-return-await:
        - error
    no-var:
        - error
    prefer-const:
        - error
    no-multiple-empty-lines:
        - error

root: true
overrides:
    [
        {
            files: ['*.ts', '*.tsx'],
            parserOptions: { project: ['./tsconfig.json'] },
            rules:
                {
                    '@typescript-eslint/no-misused-promises':
                        [
                            'error',
                            {
                                'checksVoidReturn':
                                    {
                                        'attributes': false,
                                        'properties': false,
                                    },
                            },
                        ],
                },
        },
        {
            files: ['**/*.stories.*'],
            rules:
                {
                    'import/no-anonymous-default-export': 'off',
                    'no-console': 'off',
                },
        },
    ]
